services:
  # Servidor Web
  web:
    image: nginx:alpine
    container_name: mi_servidor_web
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
    depends_on:
      - db

  # Base de Datos MySQL
  db:
    image: mysql:8.4
    container_name: mi_base_datos
    restart: always
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: "lolito412/"
      MYSQL_DATABASE: mi_proyecto_db
      MYSQL_USER: user_web
      MYSQL_PASSWORD: "lolito412/"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Administrador de BD (Interfaz Web)
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: mi_administrador_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD="lolito412/"
    depends_on:
      - db

volumes:
  db_data: